=== snate/tecweb/dati/commenti.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.commenti.com"
  xmlns="http://www.commenti.com"
  elementFormDefault="qualified">

  <xsd:element name="comments" type="Tcomments" />

  <xsd:complexType name="Tcomments"><xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="localita" type="Tlocalita" />
  </xsd:sequence></xsd:complexType>

  <xsd:complexType name="Tlocalita"><xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="comment" type="Tcomment" />
  </xsd:sequence>
  <xsd:attribute name="nome" type="xsd:string" use="required" />
  </xsd:complexType>

  <xsd:complexType name="Tcomment"><xsd:sequence>
    <xsd:element name="corpo" type="xsd:string" />
    <xsd:element name="pubblicationDate" type="xsd:date" />
  </xsd:sequence>
  <xsd:attribute name="user" type="xsd:string" use="required" />
</xsd:complexType>

</xsd:schema>

=== snate/tecweb/public_html/cgi-bin/commenti.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="commenti.xsl"?>
<c:comments xmlns="http://www.commenti.com" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xmlns:c="http://www.commenti.com" xs:schemaLocation="http://www.commenti.com commenti.xsd">

  <localita nome="zakynthos">
    <comment user="John Reese">
      <corpo>
        Stiamo come i pazzi
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="london">
    <comment user="Nate">
      <corpo>
        CAZZETTE, Terry B! - Blind Heart (Radio Edit)
      </corpo>
      <pubblicationDate>
        2012-10-21
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="madonnadicampiglio">
    <comment user="Fede">
      <corpo>
        Commento Madonna di Campiglio
      </corpo>
      <pubblicationDate>
        2012-06-14
      </pubblicationDate>
    </comment>
    <comment user="Pippo">
      <corpo>prova prova prova</corpo>
      <pubblicationDate>2004-10-02</pubblicationDate>
    </comment>
</localita>

  <localita nome="praga">
  <comment user="Fede">
      <corpo>
        Commento Praga
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="paris">
  <comment user="Fede">
      <corpo>
        Commento Parigi
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

</c:comments>

=== snate/tecweb/dati/commenti.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="commenti.xslt"?>
<comments xmlns="http://www.commenti.com"
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:schemaLocation="http://www.commenti.com commenti.xsd">

  <localita nome="zante">
    <comment user="John Reese">
      <corpo>
        Stiamo come i pazzi
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="londra">
    <comment user="Nate">
      <corpo>
        CAZZETTE, Terry B! - Blind Heart (Radio Edit)
      </corpo>
      <pubblicationDate>
        2012-10-21
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="madonna">
  </localita>

  <localita nome="praga">
  </localita>

  <localita nome="parigi">
  </localita>

</comments>

=== snate/tecweb/public_html/dati/commenti.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="commenti.xsl"?>
<comments xmlns="http://www.commenti.com"
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:schemaLocation="http://www.commenti.com commenti.xsd">

  <localita nome="zante">
    <comment user="John Reese">
      <corpo>
        Stiamo come i pazzi
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="londra">
    <comment user="Nate">
      <corpo>
        CAZZETTE, Terry B! - Blind Heart (Radio Edit)
      </corpo>
      <pubblicationDate>
        2012-10-21
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="madonna di campiglio">
  <comment user="Fede">
      <corpo>
        Commento Madonna di Campiglio
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="praga">
  <comment user="Fede">
      <corpo>
        Commento Praga
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

  <localita nome="parigi">
  <comment user="Fede">
      <corpo>
        Commento Parigi
      </corpo>
      <pubblicationDate>
        2012-06-12
      </pubblicationDate>
    </comment>
  </localita>

</comments>
