=== snate/tecweb/dati/utenti.xsd
<?xml version="1.0"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.utenti.com"
  xmlns="http://www.utenti.com"
  elementFormDefault="qualified">

  <xsd:element name="utenti" type="Tutenti" />

  <xsd:complexType name="utenti"><xsd:sequence minOccurs="0" maxOccurs="unbounded">
    <xsd:element name="user" type="Tuser" />
  </xsd:sequence></xsd:complexType>

  <xsd:complexType name="Tuser"><xsd:sequence>
    <xsd:element name="username" type="xsd:string" />
    <xsd:element name="password" type="xsd:string" />
    <xsd:element name="registrationDate" type="xsd:date" />
  </xsd:sequence></xsd:complexType>

</xsd:schema>

=== snate/tecweb/public_html/dati/utenti.xml
<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="utenti.xslt"?>
<utenti xmlns="http://www.utenti.com"
  xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:schemaLocation="http://www.utenti.com utenti.xsd">
  <user>
    <username>Nate</username>
    <password>gecko</password>
    <registrationDate>2014-11-01</registrationDate>
  </user>
  <user>
    <username>John Reese</username>
    <password>koala</password>
    <registrationDate>2010-05-24</registrationDate>
  </user>
</utenti>
