=== snate/tecweb/public_html/dati/localita.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.localita.com"
  xmlns="http://www.localita.com"
  elementFormDefault="qualified">

<xsd:element name="localita" type="Tlocalita" />

<xsd:complexType name="Tlocalita">
	<xsd:sequence maxOccurs="unbounded">
		<xsd:element name="place" type="Tplace" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Tplace">
	<xsd:sequence>
		<xsd:element name="contenuto" type="Tcontenuto" />
		<xsd:element name="link" type="Tlink" />
		<xsd:element name="info" type="Tinfo" />
	</xsd:sequence>
	<xsd:attribute name="categoria" type="Tcategoria" use="required" />
</xsd:complexType>

<xsd:simpleType name="Tcategoria">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Mare"/>
		<xsd:enumeration value="CittÃ "/>
		<xsd:enumeration value="Montagna"/>
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="Tcontenuto">
	<xsd:sequence>
		<xsd:element name="descrizione" type="Tdescrizione" />
		<xsd:element name="commento" type="Tcommento" minOccurs="0" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Tdescrizione">
	<xsd:sequence>
		<xsd:element name="img" type="Timg" />
		<xsd:element name="h1" type="Tcategoria" />
		<xsd:choice maxOccurs="unbounded">
			<xsd:element name="h2" type="Th" />
			<xsd:element name="h3" type="Th" />
			<xsd:element name="p" type="Tp" />
			<xsd:element name="img" type="Timg"/>
			<xsd:element name="dl" type="Tdl" />
		</xsd:choice>
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Timg">
	<xsd:attribute name="src" type="xsd:anyURI" />
	<xsd:attribute name="alt" type="xsd:string" />
	<xsd:attribute name="id" type="xsd:string" use="optional"/>
	<xsd:attribute name="class" type="xsd:string"  use="optional"/>
</xsd:complexType>

<xsd:complexType name="Th" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="span" type="Tspan" />
		<xsd:element name="abbr" type="Tabbr" />
	</xsd:choice>
</xsd:complexType>

<xsd:complexType name="Tp" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="span" type="Tspan" />
		<xsd:element name="abbr" type="Tabbr" />
		<xsd:element name="a" type="Ta" />
		<xsd:element name="em" type="Th" />
	</xsd:choice>
</xsd:complexType>

<xsd:complexType name="Tspan" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="abbr" type="Tabbr"/>
	</xsd:choice>	
	<xsd:attribute name="lang" type="xsd:string" />
	<xsd:attribute name="class" type="xsd:string" use="optional" />
</xsd:complexType>

<xsd:complexType name="Tabbr" >
	<xsd:simpleContent>
		<xsd:extension base="xsd:string">
			<xsd:attribute name="title" type="xsd:string" />
		</xsd:extension>	
	</xsd:simpleContent>
</xsd:complexType>

<xsd:complexType name="Ta" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="span" type="Tspan" />
		<xsd:element name="abbr" type="Tabbr" />
	</xsd:choice>
	<xsd:attribute name="href" type="xsd:anyURI" />
	<xsd:attribute name="title" type="xsd:string" />
	<xsd:attribute name="tabindex" type="xsd:positiveInteger" />
</xsd:complexType>

<xsd:complexType name="Tdl">
	<xsd:sequence maxOccurs="unbounded">
		<xsd:element name="dt" type="Th" />
		<xsd:element name="dd" type="Tdd" />
	</xsd:sequence>
	<xsd:attribute name="id" type="xsd:string" use="optional" />
	<xsd:attribute name="class" type="xsd:string" use="optional" />	
</xsd:complexType>

<xsd:complexType name="Tdd" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="span" type="Tspan" />
		<xsd:element name="abbr" type="Tabbr" />
		<xsd:element name="img" type="Timg" />
		<xsd:element name="a" type="Ta" />
		<xsd:element name="em" type="Th" />
	</xsd:choice>
</xsd:complexType>

<xsd:complexType name="Tlink">
	<xsd:sequence>
		<xsd:element name="h1" type="Th1link" />
		<xsd:element name="ul" type="Tullink"  maxOccurs="2"/>
	</xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="Th1link">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="Link utili:" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="Tullink">
	<xsd:sequence>
		<xsd:element name="li" type="Tlilink" maxOccurs="unbounded"/>
	</xsd:sequence>
	<xsd:attribute name="id" type="Tidlink" />
</xsd:complexType>

<xsd:simpleType name="Tidlink">
	<xsd:restriction base="xsd:string">
		<xsd:enumeration value="government" />
		<xsd:enumeration value="utility" />
	</xsd:restriction>
</xsd:simpleType>

<xsd:complexType name="Tlilink">
	<xsd:sequence>
	 <xsd:element name="a" type="Ta" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Tinfo">
	<xsd:sequence>
		<xsd:element name="h1" type="xsd:string" />
		<xsd:element name="dl" type="Tdlinfo" />
	</xsd:sequence>
</xsd:complexType>

<xsd:complexType name="Tdlinfo">
	<xsd:sequence maxOccurs="unbounded">
		<xsd:element name="dt" type="xsd:string" />
		<xsd:element name="dd" type="Tddlink" />
	</xsd:sequence>
	<xsd:attribute name="class" type="xsd:string" fixed="info" />	
</xsd:complexType>

<xsd:complexType name="Tddlink" mixed="true">
	<xsd:choice minOccurs="0" maxOccurs="unbounded">
		<xsd:element name="span" type="Tspan" />
		<xsd:element name="abbr" type="Tabbr" />
	</xsd:choice>
</xsd:complexType>

<xsd:complexType name="Tcommento">
	<xsd:sequence>
		<xsd:element name="corpo" type="xsd:string" />
		<xsd:element name="dataPubblicazione" type="xsd:date" />
	</xsd:sequence>
	<xsd:attribute name="user" type="xsd:string" use="required" />
</xsd:complexType>

</xsd:schema>

=== snate/tecweb/public_html/dati/localita.xml
<?xml version="1.0" encoding="utf-8"?>
<localita xmlns="http://www.localita.com"
xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance"
xsd:schemaLocation="http://www.localita.com localita.xsd">

<place categoria="Città">
	<descrizione>
		<img src="../images/london_1.jpg" alt="Foto di Londra" id="img_presentazione" />
		<h1>Città</h1>
		<h2>Londra - <span lang="en">London</span></h2>
		<p>
		Londra è la città più popolata di tutta Europa: in questo
		posto le persone migrano per cercare fortuna e per essere in continuo
		contatto con persone di tutte le culture. È inoltre dotata di
		infrastrutture e servizi molto avanzati sia per i turisti che per chi
		vi abita.
		</p>
		<h3>Trasporti</h3>
		<p>
		Se volete andare a Londra, uno dei mezzi più comodi e
		caratteristici di questa città è la metropolitana,
		chiamata in lingua inglese <span lang="en">Tube</span> oppure
		<span lang="en"><abbr title="Docklands Light Railway">DLR</abbr></span>,
		ovvero la metropolitana leggera. Vi è inoltre il servizio
		ferroviario urbano (chiamato <span lang="en">Overground</span>) e
		moltissimi bus rossi, caratteristici anche questi della città.
		Varie agenzie offrono dei biglietti per poter viaggiare un giorno o
		due su questi mezzi, a bordo dei quali si può sentire una guida
		in lingua inglese dal vivo o altrimenti nella propria lingua.
		</p>
		<img src="../images/london_1.png" alt="Mappa della metropolitana di Londra" class="img_content"/>
		<h3>Vita notturna</h3>
		<p>
		Londra riesce ad accontentare i gusti di ogni persona che vi viaggia:
		la capitale inglese è piena di locali etnici che presentano
		piatti di quasi tutte le culture del mondo, <span lang="en">club
		</span> di tutti i tipi. Se una persona preferisce farsi una passeggiata
		nel centro cittadino, rimarrà colpita dalle luci notturne della
		città e dagli spettacolari effetti che queste creano combinandosi
		tra loro.
		</p>
		<img src="../images/london_2.jpg" alt="Londra di notte" class="img_content" />
		<h3>Parchi</h3>
		<p>
		Sebbene sia la capitale europea più popolata, non immaginatevi
		Londra come una metropoli grigia e cupa; viene dedicata una particolare
		attenzione agli spazi verdi, lasciando a bocca aperta i visitatori di
		tutto il mondo quando vi si trovano di fronte.
		</p>
		<dl class="sights">
		<dt>
		  <span lang="en">Hyde Park</span>
		</dt>
		<dd>
		  <span lang="en">Hyde Park</span> è uno dei parchi più
		  conosciuti di questa città. Questo parco è diviso a
		  metà dal <span lang="en">Serpentine Lake</span> in due
		  parchi: il vero e proprio <span lang="en">Hyde Park</span> e
		  i <span lang="en">Kensington Gardens</span>, considerati
		  formalmente separati ma di fatto costituiscono un unico parco. Uno
		  dei quattro angoli di questo parco è il <span lang="en">
		  The Speakers' Corner</span>, ovvero una piccola zona dove chiunque
		  viene chiamato a esprimere in piena libertà la propria
		  opinione; personaggi illustri che hanno sfruttato questo posto per
		  dar sfogo alle proprie idee sono Karl Marx, Lenin, <span lang="en">
		  George Orwell</span>(una cui casa è presente a <span lang="en">
		  Notting Hill</span>) e <span lang="en">William Morris</span>.
		  <img src="../images/london_3.jpg" alt="Hyde Park" class="img_content"/>
		</dd>
		<dt>
		  <span lang="en">Regent's Park</span>
		</dt>
		<dd>
		  Questo parco ottocentesco, realizzato da <span lang="en">John
		  Nash</span>, è uno dei parchi imperiali ed è situato
		  nella zona di <span lang="en">Westminster</span>. In questo parco
		  si trova il <span lang="en">London Zoo</span>, lo zoo più
		  antico del mondo e vi si possono ammirare una quantità
		  impensabile di animali.
		  <img src="../images/london_4.jpg" alt="Regent's Park" class="img_content"/>
		</dd>
		<dt>
		  <span lang="en">Green Park</span>
		</dt>
		<dd>
		  <span lang="en">Green Park</span> è un altro dei parchi
		  imperiali di Londra. Questo parco è raggiungibile tramite un
		  ingresso direttamente alla destra dell'entrata principale di
		  <span lang="en">Buckingham Palace</span>, dove ogni due giorni
		  viene svolta la sfarzosa cerimonia del cambio della guardia.
		  Attraversando questo parco si può arrivare direttamente a
		  <span lang="en">Piccadilly Circus</span>, piazza caratteristica
		  ricordata da tutti i turisti grazie alle sue enormi pubblicità
		  a LED.
		  <img src="../images/london_5.jpg" alt="Ingresso di Buckingham Palace" class="img_content"/>
		</dd>
		</dl>
	</descrizione>	
		 
	<link>
		<h1>Link utili:</h1>
        <ul id="government">
          <li><a href="http://www.cityoflondon.gov.uk/Pages/default.aspx" title="Sito della città" tabindex="8">Londra (EN)</a></li>
          <li><a href="http://www.visitlondon.com/it/" title="Sito per i turisti della città" tabindex="9">Sito per turisti - Londra (IT)</a></li>
          <li><a href="https://www.tfl.gov.uk/" title="Trasporti a Londra" tabindex="10">Trasporti a Londra (EN)</a></li>
        </ul>
        <ul id="utility">
          <li><a href="http://www.londontown.com/" title="Offerte a Londra" tabindex="11">Offerte per la vita a Londra (EN)</a></li>
          <li><a href="http://www.ministryofsound.com/" title="Sito del Ministry Club" tabindex="12"><span lang="eng">Ministry Club</span> (EN)</a></li>
          <li><a href="http://www.speakerscorner.net/" title="Sito dello Speakers' Corner" tabindex="13"><span lang="eng">Speakers' Corner</span> (EN)</a></li>
          <li><a href="http://www.zsl.org/zsl-london-zoo" title="Zoo di Londra" tabindex="14"><span lang="eng">London Zoo</span> (EN)</a></li>
          <li><a href="http://www.changing-the-guard.com/dates-times.html" title="Orari del cambio della guardia" tabindex="15">Cambio della guardia (EN)</a></li>
        </ul>
	</link>
	
	<info>
        <h1>LONDRA</h1>
        <dl class="info">
          <dt>Nazione:</dt>
            <dd>Regno Unito</dd>
          <dt>Abitanti:</dt>
            <dd>8400000</dd>
          <dt>Superficie:</dt>
            <dd>1550 <abbr title="chilometri">km</abbr><span class="square">2</span></dd>
          <dt>Posizione:</dt>
            <dd>Inghilterra centrale</dd>
        </dl>
	</info>
</place>

<place categoria="Città">	
	<descrizione>
		<img src="../images/parigi_0.jpg" alt="Foto di Parigi" id="img_presentazione" />
		<h1>Città</h1>
		<h2>Parigi - <span lang="fr">Paris</span></h2>
		<p>
        Parigi, capitale della Francia, è una delle mete più
        romantiche dove potete andare. Questa città ospita
        numerosi musei, collezioni d'arte e monumenti che la rendono
        singolare. Questa città uggiosa, attraversata
        dalla Senna, si divide in 20 <span lang="fr">arrondissment</span>
        che si svolgono a spirale a partire dal centro della città.
		</p>
		<p>
		Uno di questi, <span lang="fr">Montmartre</span>, è
		il famoso quartiere dove si trova il <span lang="fr">Moulin
		Rouge</span> ed è pieno di ristoranti e di negozi di
		<span lang="fr">souvenir</span> e si può salire
		facilmente al <span lang="fr">Sacré-Cœur</span>.
		</p>
		<h3>Trasporti</h3>
		<p>
        Ci sono vari modi per spostarsi a Parigi:
		</p>
		<dl id="trasporti">
        <dt>
  	      Metropolitana
		</dt>
        <dd>
          Il servizio metropolitano di Parigi é attivo sette giorni su
          sette, dall'alba alle 01:20 di notte. Le fermate, presenti in
          gran numero sul territorio della capitale francese, sono ben
          riconoscibili grazie a delle pittoresche insegne poste alle
          entrate di queste.
          <img src="../images/parigi_1.jpg" alt="Insegna di una metropolitana parigina" class="img_content"/>
        </dd>
        <dt>
          Altre
        </dt>
        <dd>
          Parigi offre anche un servizio di trasporti in bus o tram, che
          però è molto più lento delle metropolitane
          ma possono essere più gradevoli da utilizzare per un
          turista così da poter ammirare le attrazioni della
          città lungo il tragitto. Un'altra alternativa è
          il bike sharing, dal momento che si trovano molte stazioni in
          città dove si può usufruire di questo servizio.
          <img src="../images/parigi_2.jpg" alt="Bus parigino" class="img_content"/>
        </dd>
		</dl>
		<h3>Arte</h3>
		<p>
        Ci sono molti musei a Parigi; uno di questi è il <span lang="fr">
	    Centre Pompidou</span>, progettato dall'italiano Renzo Piano e
  	    da <span lang="en">Richard Rogers</span>, con tutta la
	    struttura che si sviluppa sull'esterno per lasciare spazio alle
	    opere d'arte all'interno dell'edificio. Un altro famosissimo museo
	    è il <span lang="fr">Louvre</span>, dove si trovano
	    opere d'arte come la Gioconda di Leonardo Da Vinci o Amore e
	    Psiche del Canova.
		</p>
		<img src="../images/parigi_3.jpg" alt="Louvre di Parigi" class="img_content"/>
	</descrizione>
	
	<link>
		<h1>Link utili:</h1>
        <ul id="government">
          <li>
            <a href="http://www.paris.fr/english" title="Sito della città" tabindex="8">
              Parigi (EN)
            </a>
          </li>
          <li>
            <a href="http://en.parisinfo.com/" title="Sito per i turisti della città" tabindex="9">
              Sito per turisti - Parigi (EN)
            </a>
          </li>
          <li>
            <a href="http://www.ratp.fr/en/ratp/c_21879/visiting-paris/" title="Sito dei trasporti di Parigi" tabindex="10">
              Trasporti a Parigi (EN)
            </a>
          </li>
        </ul>
        <ul id="utility">
          <li>
            <a href="http://www.lastminute.com/city-breaks/paris.html" title="Offerte per viaggi" tabindex="11">
              Offerte viaggi a Parigi (EN)
            </a>
          </li>
          <li>
            <a href="https://www.centrepompidou.fr/en" title="Sito del Pompidou Centre" tabindex="12">
              <span lang="fr">Pompidou Centre</span> (EN)
            </a>
          </li>
          <li>
